name: .NET

on:
  push:
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release
      working-directory: template-parser
      
    - name: Publish Linux
      run: dotnet publish --no-restore --no-build -r linux-x64 -c Release
      working-directory: template-parser
      
    - name: Publish Windows
      run: dotnet publish -r win-x64 -c Release
      
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./template-parser/bin/Release/net7.0/linux-x64/publish/Template.Parser.Cli
          ./template-parser/bin/Release/net7.0/win-x64/publish/Template.Parser.Cli.exe
    
