name: Build, Test, Publish and Release

on:
  push:
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release --logger trx --results-directory "TestResults"

    - name: Upload unit test results
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-results
        path: TestResults
      if: ${{ always() }}

    - name: Publish Linux
      run: dotnet publish --no-restore --no-build -r linux-x64 -c Release
      working-directory: template-parser

    - name: Publish Windows
      run: dotnet publish -r win-x64 -c Release

    - name: Publish MacOS (arm)
      run: dotnet publish --no-restore --no-build -r osx-arm64 -c Release

    - name: Publish MacOS (x64)
      run: dotnet publish --no-restore --no-build -r osx-x64 -c Release

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./template-parser/bin/Release/net8.0/linux-x64/publish/Template.Parser.Cli
          ./template-parser/bin/Release/net8.0/win-x64/publish/Template.Parser.Cli.exe
          ./template-parser/bin/Release/net8.0/osx-arm64/publish/Template.Parser.Cli
          ./template-parser/bin/Release/net8.0/osx-x64/publish/Template.Parser.Cli
